### ISSUE TITLE
Problems updating path nupack-4.0.1.8/source/package in MacOS

### ISSUE THREAD

**Issue by sofiromano** [InfluenceFunctional/E2EDNA2#10]
I've been unsuccessfully trying to set up E2EDNA2 in my Mac. I've followed the steps but I'm unsure if I correctly updated the path of /nupack-4.0.1.8/source/package. I copied the path /Users/..etc and open the macos_installation.sh file with nano. Then I updated the file as follows:
echo INSTALLING NUPACK
python -m pip install -U nupack -f
/Users/(...etc)/nupack-4.0.1.8/source/package

When I run the file everything looks ok except nupack, I get the following error: 

ERROR: Could not find a version that satisfies the requirement nupack (from versions: none)
ERROR: No matching distribution found for nupack

If I try with the following path /nupack-4.0.1.8/source/package/setup.py I get the message:
-f option requires 1 argument
macos_installation.sh: line 13: /Users/(..etc)/nupack-4.0.1.8/source/package/setup.py: Permission denied

What should I try next?

**Comment by InfluenceFunctional** [comment]
There was recently a major update to Nupack - possibly this is driving the problem? I hope you were able to get it fixed!

**Comment by taoliu032** [comment]
There is another way of surmounting the nupack issue: you could choose to install the entire conda virtual environment using a yaml file (I changed the file extension from .yml to .txt so that it can be uploaded here) then to create the environment, simply:
`conda env create --file e2edna_conda_env.yml`
To activate it:
`conda activate e2edna_conda_env`

Let us know if it works.

[e2edna_conda_env.txt](https://github.com/InfluenceFunctional/E2EDNA2/files/11507890/e2edna_conda_env.txt)

**Comment by sofiromano** [comment]
Hi All, 
I downloaded again nupack and kept it in the Downloads folder. I updated the path in macos_installation.sh file and it worked! Thanks for your help!
